name: Python CI

on: [push]

env:  
  NEO4J_USER: neo4j
  NEO4J_PASSWORD: password
  NEO4J_CONTAINER_NAME: test

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:latest
        options: > 
          --name test
        volumes:
          - ./data:/data:Z
          - ./plugins:/plugins:Z
        ports:                    
        - 7474:7474 # used for http
        - 7687:7687 # used for bolt
        env:       
          NEO4J_AUTH: ${{ env.NEO4J_USER }}/${{ env.NEO4J_PASSWORD }} 
          NEO4J_apoc_export_file_enabled: "true"
          NEO4J_apoc_import_file_enabled: "true"
          NEO4J_apoc_import_file_use__neo4j__config: "true"
          NEO4J_dbms_connector_bolt_advertised__address: localhost:7687
          NEO4JLABS_PLUGINS: '["apoc", "apoc-extended"]'

    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v5
      with:
        python-version: '3.14'
        cache: 'pip'
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: start db
      run: docker start ${{env.NEO4J_CONTAINER_NAME}}
        

    - name: test jsonToTCM
      run: python3.14 arcane2graph/jsonToTCM.py test
    - name: test TCMtoTSM
      run: python3.14 arcane2graph/TCMtoTSM.py test
    - name: test TSMtoDB
      run: |
        docker ps
        docker ps -a
        python3.14 arcane2graph/TSMtoNeo4j.py test bolt://localhost:7687 ${{ env.NEO4J_USER }} ${{ env.NEO4J_PASSWORD }}
    
