name: Python CI

on:
  workflow_dispatch:
  pull_request: 
  push:
    branches: [ main ]
    paths-ignore:
      - '**.jar'
      - '**.yml'

env:  
  NEO4J_USER: neo4j
  NEO4J_PASSWORD: password
  NEO4J_CONTAINER_NAME: test

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: create service
        run: | 
          docker create --label eb4219 --name test -p 7474:7474 -p 7687:7687 \
          --health-cmd "cypher-shell -u neo4j -p password 'RETURN 1;' || exit 1" --health-interval 2s --health-timeout 5s --health-retries 10 \
          -e "NEO4J_AUTH=neo4j/password" -e "NEO4J_apoc_export_file_enabled=true" -e "NEO4J_apoc_import_file_enabled=true" \
          -e "NEO4J_apoc_import_file_use__neo4j__config=true" -e "NEO4J_PLUGINS=[\"apoc\", \"apoc-extended\"]" \
          -e GITHUB_ACTIONS=true -e CI=true \
          -v ${{github.workspace}}/my_plugins:/plugins \
          neo4j:latest
          docker start test
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'
          cache: 'pip'
          
      - name: Install Dependencies
        run: pip install -e ".[dev]"

      - name: run tests not needing neo4j
        run: python -m unittest tests/test_1_json_to_tcm.py tests/test_2_tcm_to_tsm.py -v
      
      - name: wait for neo4j container
        run: |
          timeout=30
          sleep_time=2

          is_healthy=$(docker inspect --format="{{if .Config.Healthcheck}}{{.State.Health.Status}}{{end}}" test)
          while [ $is_healthy != 'healthy' ] && [ $is_healthy != 'unhealthy' ] && [ $timeout >= 0 ]; do
            echo "neo4j state : $is_healthy"
            timeout=$timeout-$sleep_time
            sleep $sleep_time
            is_healthy=$(docker inspect --format="{{if .Config.Healthcheck}}{{.State.Health.Status}}{{end}}" test)
          done
          
          echo neo4j container is healthy
      
      - name: run tests needing neo4j
        run: python -m unittest tests/test_3_tsm_to_neo4j.py tests/test_4_tcm_to_neo4j.py tests/test_5_db_to_tsm.py -v

