name: Triggered by Repository B

on:
  repository_dispatch:
    types: [repository-b-completed]

jobs:
  do-something:
    runs-on: ubuntu-latest

    steps:
      - name: Show information from Repository B
        run: |
          echo "Repository B finished"

      - name: Do the actual work
        run: |
          echo "Doing work in Repository A"